spring.datasource.username=wpuser
spring.datasource.password=password
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/wp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=always


spring.flyway.user=wpadmin
spring.flyway.password=password
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.properties.hibernate.dialect=com.mysql.cj.jdbc.Driver
#spring.jpa.defer-datasource-initialization=false
#spring.flyway.locations=classpath:db/migration/common,classpath:db/migration/{vendor}



server.port=8082